### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Raging-Beard** [nickhod/aeroscenery#6]
I just get an error...

Object reference not set to an instance of an object.
   at AeroScenery.Data.RegistryExtensions.GetValueAsBoolean(RegistryKey key, String name, Boolean defaultValue)
   at AeroScenery.Data.RegistryService.GetSettingsLegacy()
   at AeroScenery.Data.SettingsService.GetSettings()
   at AeroScenery.AeroSceneryManager.Initialize()
   at AeroScenery.Program.Main()

**Comment by nickhod** [comment]
Should be fixed in 1.0.1

**Comment by Raging-Beard** [comment]
Thanks, 0.6 worked :)

**Comment by nickhod** [comment]
Would you mind giving the new version, 1.0.1 a try:

https://github.com/nickhod/aeroscenery/releases/download/1.0.1/AeroScenery.msi

it's got a lot of other things fixed, so you'll probably want to use that version. (If it works for you).

**Comment by Raging-Beard** [comment]
That one installs and opens perfectly, thank you.

Can I change what drive Aeroscenery downloads and works on?

**Comment by nickhod** [comment]
Great.

Yes, go into settings (top left) and change the "Working Directory" path to whatever you want it to be.

(I really need to write some docs!)
